version: 2

models:
  - name: stg_orders
    description: "Staging table for normalized order data from multiple sources"
    columns:
      - name: order_key
        description: "Unique identifier for each order"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "External order ID from source system"
        tests:
          - not_null
      - name: user_id
        description: "User who placed the order"
        tests:
          - not_null
      - name: workspace_id
        description: "Workspace identifier for multi-tenant support"
        tests:
          - not_null
      - name: total_price
        description: "Total order amount"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: order_date
        description: "Date when order was placed"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: "'2020-01-01'"
              max_value: "current_date + interval '1 day'"
      - name: status
        description: "Order status"
        tests:
          - not_null
          - accepted_values:
              values: ['pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', 'completed']
      - name: currency
        description: "Order currency"
        tests:
          - not_null
          - accepted_values:
              values: ['USD', 'EUR', 'GBP', 'CAD']
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - order_id
            - source_platform
            - workspace_id

  - name: stg_campaigns
    description: "Staging table for normalized campaign data"
    columns:
      - name: campaign_key
        description: "Unique identifier for each campaign record"
        tests:
          - unique
          - not_null
      - name: campaign_id
        description: "External campaign ID from Meta"
        tests:
          - not_null
      - name: workspace_id
        description: "Workspace identifier"
        tests:
          - not_null
      - name: campaign_date
        description: "Date of campaign performance data"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: "'2020-01-01'"
              max_value: "current_date + interval '1 day'"
      - name: total_spend
        description: "Total campaign spend"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: impressions
        description: "Total impressions"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: clicks
        description: "Total clicks"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: calculated_roas
        description: "Calculated ROAS"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - campaign_id
            - campaign_date
            - workspace_id

  - name: dim_products
    description: "Product dimension table with enriched product data"
    columns:
      - name: product_key
        description: "Unique surrogate key for each product"
        tests:
          - unique
          - not_null
      - name: product_id
        description: "Source product identifier"
        tests:
          - not_null
      - name: product_name
        description: "Product name"
        tests:
          - not_null
      - name: sku
        description: "Stock keeping unit"
        tests:
          - not_null
      - name: workspace_id
        description: "Workspace identifier"
        tests:
          - not_null
      - name: price
        description: "Product price"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: cost_per_unit
        description: "Cost of goods sold per unit"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: stock_quantity
        description: "Current stock quantity"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: profit_margin_percent
        description: "Profit margin percentage"
        tests:
          - not_null
      - name: stock_status
        description: "Stock status category"
        tests:
          - not_null
          - accepted_values:
              values: ['out_of_stock', 'low_stock', 'medium_stock', 'high_stock']
      - name: price_tier
        description: "Price tier category"
        tests:
          - not_null
          - accepted_values:
              values: ['budget', 'mid_range', 'premium', 'luxury']
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - product_id
            - source_system
            - workspace_id

sources:
  - name: public
    description: "Public schema in Supabase Postgres"
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: orders
        description: "Raw orders table"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: order_id
            tests:
              - unique
              - not_null
          - name: total_price
            tests:
              - not_null
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
      
      - name: meta_campaigns
        description: "Raw Meta campaigns table"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: campaign_id
            tests:
              - not_null
        freshness:
          warn_after: {count: 2, period: hour}
          error_after: {count: 6, period: hour}
      
      - name: products
        description: "Raw products table"
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: sku
            tests:
              - unique
              - not_null
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
      
      - name: shopify_orders
        description: "Raw Shopify orders table"
        freshness:
          warn_after: {count: 6, period: hour}
          error_after: {count: 12, period: hour}
      
      - name: shopify_products
        description: "Raw Shopify products table"
        freshness:
          warn_after: {count: 24, period: hour}
          error