name: 'ecom_metrics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ecom_metrics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  ecom_metrics:
    # Config indicated by + and applies to all files under models/example/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: metrics
    intermediate:
      +materialized: view
      +schema: intermediate

# Configure seeds
seeds:
  ecom_metrics:
    +schema: seeds

# Configure tests
tests:
  +store_failures: true
  +schema: test_failures

# Configure snapshots
snapshots:
  ecom_metrics:
    +target_schema: snapshots

vars:
  # dbt-utils variables
  'dbt_utils:dispatch_list': ['dbt_utils']
  
  # Project-specific