ecom_metrics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db.ltchmrlcudvwukslicty.supabase.co
      user: postgres
      password: "{{ env_var('SUPABASE_DB_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 4
      keepalives_idle: 0
      search_path: "public"
      sslmode: require
    prod:
      type: postgres
      host: db.ltchmrlcudvwukslicty.supabase.co
      user: postgres
      password: "{{ env_var('SUPABASE_DB_PASSWORD') }}"
      port: 5432
      dbname: postgres
      schema: metrics
      threads: 4
      keepalives_idle: 0
      search_path: "public,metrics"
      sslmode: require